"""Render results/REPORT_C.md (Module C) from the JSON results."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from . import config
from .pricing import BOOK_LABEL, BOOKS, N_VARIANTS, RULE_LABEL, RULES


def _c1(c1: dict) -> str:
    md = "| Book | RV window | b_VRP (bps per 100 %²) | NW t | b_RV (bps per 100 %²) | NW t | VIX² alone: b | t | R² | N |\n|---|---|---|---|---|---|---|---|---|---|\n"
    for book in BOOKS:
        if book not in c1:
            continue
        for w, r in c1[book].items():
            md += (f"| {BOOK_LABEL[book]} | {w} | {r['b_vrp_bps_per_100var']:.2f} | {r['t_vrp_nw']:.2f} | {r['b_rv_bps_per_100var']:.2f} | "
                   f"{r['t_rv_nw']:.2f} | {r['b_vix2_alone']:.2f} | {r['t_vix2_alone']:.2f} | {r['r2']:.4f} | {r['n']:,} |\n")
    return md


def _c2(c2: dict) -> str:
    md = ""
    for book in BOOKS:
        if book not in c2:
            continue
        sr = pd.DataFrame(c2[book]["sharpe_by_rv_then_vrp"]).T
        n = pd.DataFrame(c2[book]["n_by_rv_then_vrp"]).T
        md += f"\n**{BOOK_LABEL[book]}** — annualised Sharpe; rows = realised-variance tercile (low→high), columns = VRP tercile within it (low→high).\n\n"
        md += "| RV tercile | VRP low | VRP mid | VRP high | N per cell |\n|---|---|---|---|---|\n"
        for i, (idx, row) in enumerate(sr.iterrows()):
            md += f"| {['low', 'mid', 'high'][i]} | {row.iloc[0]:.2f} | {row.iloc[1]:.2f} | {row.iloc[2]:.2f} | {int(n.iloc[i].iloc[0]):,} |\n"
        md += (f"\nRV terciles where high-VRP Sharpe > low-VRP Sharpe: **{c2[book]['rv_terciles_where_high_vrp_beats_low']} of 3**. "
               f"Reverse sort — VRP terciles where high-RV Sharpe > low-RV Sharpe: **{c2[book]['vrp_terciles_where_high_rv_beats_low']} of 3**.\n")
    return md


def _rules(rules: dict) -> str:
    md = ""
    keys = ["constant", "vix_rule", "vrp_median", "vrp_pos", "backwardation", "constant_2008_on", "vix_rule_2008_on"]
    labels = {**RULE_LABEL, "constant_2008_on": "constant, 2008+ only", "vix_rule_2008_on": "VIX rule, 2008+ only"}
    for book in BOOKS:
        if book not in rules:
            continue
        R = rules[book]
        md += f"\n**{BOOK_LABEL[book]}**, net of the book's pre-registered costs.\n\n"
        md += "| Rule | net Sharpe | ann. net return | ann. vol | max DD | share days on | NW t of mean | spanning α vs constant (t) | vs VIX rule (t) |\n|---|---|---|---|---|---|---|---|---|\n"
        for k in keys:
            if k not in R:
                continue
            p = R[k]
            sa = R.get(f"{k}_vs_constant"); sv = R.get(f"{k}_vs_vix_rule")
            md += (f"| {labels[k]} | {p['sharpe_net']:.2f} | {p['ann_return_net']*100:.1f}% | {p['ann_vol']*100:.1f}% | {p['max_drawdown']*100:.0f}% | "
                   f"{p['share_days_on']*100:.0f}% | {p['t_mean_net_nw']:.2f} | "
                   + (f"{sa['alpha_bps_per_day']:.2f} bps ({sa['t_alpha_nw']:.2f})" if sa else "") + " | "
                   + (f"{sv['alpha_bps_per_day']:.2f} bps ({sv['t_alpha_nw']:.2f})" if sv else "") + " |\n")
    return md


def _grid(records: list[dict]) -> str:
    md = "| book | RV window | rule | net Sharpe | constant, same days | ann. net return | share days on | N |\n|---|---|---|---|---|---|---|---|\n"
    for r in records:
        md += (f"| {BOOK_LABEL[r['book']]} | {r['rv_window']} | {RULE_LABEL[r['rule']]} | {r['sharpe_net']:.2f} | {r['sharpe_net_constant_same_days']:.2f} | "
               f"{r['ann_return_net']*100:.1f}% | {r['share_days_on']*100:.0f}% | {r['n_days']:,} |\n")
    return md


def write_report_c(is_res: dict, oos_res: dict | None, out_dir: Path) -> None:
    md = ["# Module C results report (auto-generated by `run_all.py`)\n",
          f"Generated {is_res['generated_utc']}. In-sample ends {config.IS_END.date()}; held-out {config.OOS_START.date()} → {config.OOS_END.date()}"
          + (" — **evaluated**." if oos_res else " — **locked, not evaluated in this run**.") + "\n",
          "VRP_(t−1) = VIX²_(t−1) − RV_(t−1); RV = 252 × mean of (100·r_mkt)² over the window ending t−1; units %² (VIX 20 = 400). "
          "Backwardation = VIX_(t−1) > VIX3M_(t−1), sample 2008+. Books and costs are exactly those of Modules A and B.\n",
          "## C1 — decomposition: does the premium load on the price (VRP) or the quantity (RV) of risk?\n", _c1(is_res["c1"]),
          "\n## C2 — double sorts (in-sample)\n", _c2(is_res["c2"]),
          "\n## C3 / C4 — rules, in-sample\n", _rules(is_res["rules"]),
          f"\n## Pre-registered variant grid ({N_VARIANTS} variants, in-sample)\n", _grid(is_res["grid"])]
    if oos_res:
        md += [f"\n## OUT-OF-SAMPLE {config.OOS_START.date()} → {config.OOS_END.date()} — evaluated once\n",
               "### C1 out of sample\n", _c1(oos_res["c1"]),
               "\n### Rules out of sample\n", _rules(oos_res["rules"]),
               "\n### Grid out of sample\n", _grid(oos_res["grid"])]
    (out_dir / "REPORT_C.md").write_text("\n".join(md) + "\n")
