"""Render results/REPORT.md from the JSON results so every number is traceable."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from . import config

LABEL = {"st_rev": "ST_Rev factor (all-cap)", "big_rev": "Big-cap reversal leg"}


def _pct(x): return f"{x*100:.2f}%"
def _f(x, d=2): return f"{x:.{d}f}"


def perf_md(strats: dict, universe: str) -> str:
    s = strats[universe]
    cols = [("constant", "Constant exposure"), ("timed", "VIX-timed (headline)"),
            ("timed_flat_costs", "VIX-timed, flat costs"), ("timed_costs_x2", "VIX-timed, costs ×2"),
            ("constant_costs_x2", "Constant, costs ×2")]
    rows = [("Ann. return (net)", "ann_return_net", _pct), ("Ann. return (gross)", "ann_return_gross", _pct),
            ("Cost drag / yr", "ann_cost_drag", _pct), ("Volatility", "ann_vol", _pct),
            ("Sharpe (net)", "sharpe_net", _f), ("Sharpe (gross)", "sharpe_gross", _f),
            ("Max drawdown", "max_drawdown", _pct), ("Worst month", "worst_month", _pct),
            ("Skew", "skew", _f), ("Hit rate", "hit_rate", _pct),
            ("Turnover ($ traded / $ capital / yr)", "turnover_per_year", lambda x: _f(x, 1)),
            ("Mean exposure", "mean_exposure", _f)]
    md = "| | " + " | ".join(c[1] for c in cols) + " |\n|---|" + "---|" * len(cols) + "\n"
    for name, key, fmt in rows:
        md += f"| {name} | " + " | ".join(fmt(s[c[0]][key]) for c in cols) + " |\n"
    return md


def write_report(is_res: dict, oos_res: dict | None, out_dir: Path) -> None:
    S = is_res["strategies"]
    md = ["# Results report (auto-generated by `run_all.py`)\n",
          f"Generated {is_res['generated_utc']}. In-sample {is_res['start']} → {is_res['end']} ({is_res['n_days']:,} days). "
          f"Held-out period {config.OOS_START.date()} → {config.OOS_END.date()}"
          + (" — **evaluated**." if oos_res else " — **locked, not evaluated in this run**.") + "\n",
          "Costs: one-way cost per $ traded = c_base × VIX_(t−1)/20, c_base = "
          f"{config.C_BASE_BPS['big_rev']:.0f} bps (big-cap) / {config.C_BASE_BPS['st_rev']:.0f} bps (all-cap); "
          f"book turnover τ = {config.TAU:.0%} of gross per day plus timing turnover.\n",
          "## Prediction 1 — reversal return on lagged VIX (Newey–West, 10 lags)\n",
          "| Universe | slope (bps per VIX pt) | NW t | p | R² | N |\n|---|---|---|---|---|---|"]
    for u, r in is_res["prediction_1_regression"].items():
        md.append(f"| {LABEL[u]} | {r['slope_bps_per_vix_pt']:.3f} | {r['t_slope_nw']:.2f} | {r['p_slope']:.4f} | {r['r2']:.4f} | {r['n']:,} |")
    md.append("\n## Prediction 2 — mean next-day return by lagged-VIX quintile (bps, in-sample)\n")
    md.append("| Quintile | VIX range | " + " | ".join(f"{LABEL[u]} mean ± 95% CI (ann. vol, SR, worst day)" for u in ("st_rev", "big_rev")) + " |\n|---|---|---|---|")
    qa, qb = is_res["prediction_2_quintiles"]["st_rev"], is_res["prediction_2_quintiles"]["big_rev"]
    for a, b in zip(qa, qb):
        md.append(f"| Q{a['vix_quintile']} | {a['vix_lo']:.1f}–{a['vix_hi']:.1f} | "
                  f"{a['mean_bps']:.2f} ± {1.96*a['se_bps']:.2f} ({a['ann_vol']*100:.0f}%, SR {a['ann_sharpe']:.2f}, {a['worst_day_bps']/100:.1f}%) | "
                  f"{b['mean_bps']:.2f} ± {1.96*b['se_bps']:.2f} ({b['ann_vol']*100:.0f}%, SR {b['ann_sharpe']:.2f}, {b['worst_day_bps']/100:.1f}%) |")
    for u in ("big_rev", "st_rev"):
        s = S[u]
        md.append(f"\n## {LABEL[u]} — in-sample performance, net of costs\n")
        md.append(perf_md(S, u))
        t = s["timed_vs_constant"]
        md.append(f"\nTimed vs constant (spanning regression, HAC): alpha {t['alpha_bps_per_day']:.2f} bps/day, t = {t['t_alpha_nw']:.2f}, beta on constant = {t['beta_on_benchmark']:.2f}.\n")
        fa, fc = s["factor_alpha_timed"], s["factor_alpha_constant"]
        md.append(f"FF5 + Mom alpha: timed {fa['alpha_ann']*100:.2f}%/yr (t = {fa['t_alpha_nw']:.2f}), constant {fc['alpha_ann']*100:.2f}%/yr (t = {fc['t_alpha_nw']:.2f}). "
                  f"Timed betas: Mkt {fa['beta_mkt_rf']:.3f}, SMB {fa['beta_smb']:.3f}, HML {fa['beta_hml']:.3f}, Mom {fa['beta_mom']:.3f}; R² {fa['r2']:.3f}.\n")
        md.append(f"Break-even c_base (net Sharpe = 0): timed **{s['breakeven_c_base_bps_timed']:.1f} bps**, constant **{s['breakeven_c_base_bps_constant']:.1f} bps**.\n")
        md.append("Net return by year (timed / constant):\n")
        md.append("| " + " | ".join(str(y) for y in s["by_year_timed"]) + " |\n|" + "---|" * len(s["by_year_timed"]))
        md.append("| " + " | ".join(f"{v*100:.0f}%" for v in s["by_year_timed"].values()) + " |")
        md.append("| " + " | ".join(f"{v*100:.0f}%" for v in s["by_year_constant"].values()) + " |")

    grid = pd.DataFrame(is_res["sensitivity_grid"])
    md.append("\n## Sensitivity — all 36 pre-registered variants (net Sharpe, in-sample)\n")
    for u in ("big_rev", "st_rev"):
        lin = grid[(grid.universe == u) & (grid.rule == "linear")].pivot(index="cap", columns="norm", values="sharpe_net")
        md.append(f"**{LABEL[u]}, linear rule** (rows: cap, cols: normaliser)\n")
        md.append(lin.round(2).to_markdown())
        reg = grid[(grid.universe == u) & (grid.rule == "regime")]["sharpe_net"].iloc[0]
        md.append(f"\nRegime rule (on when VIX_(t−1) above trailing-1y median): net Sharpe {reg:.2f}\n")
    md.append(f"\nExposure of the headline rule: mean {is_res['exposure']['mean_exposure']:.2f}, max {is_res['exposure']['max_exposure']:.2f}, "
              f"{is_res['exposure']['share_days_above_1']*100:.0f}% of days above 1×, {is_res['exposure']['share_days_at_cap']*100:.1f}% at the cap.\n")

    md.append("\n## Sub-periods (in-sample, same VIX bins as above)\n")
    for name, sp in is_res["subperiods"].items():
        md.append(f"**{name}** ({sp['start']} → {sp['end']}, {sp['n_days']:,} days)\n")
        md.append("| Universe | slope bps/pt | NW t | constant-exposure net Sharpe | Q1 | Q2 | Q3 | Q4 | Q5 (bps/day) |\n|---|---|---|---|---|---|---|---|---|")
        for u in ("big_rev", "st_rev"):
            r, q = sp["regression"][u], sp["quintiles"][u]
            qs = " | ".join(f"{row['mean_bps']:.1f}" if row["mean_bps"] is not None else "–" for row in q)
            md.append(f"| {LABEL[u]} | {r['slope_bps_per_vix_pt']:.3f} | {r['t_slope_nw']:.2f} | {sp['constant_sharpe_net'][u]:.2f} | {qs} |")
        md.append("")

    md.append("\n## POST-HOC (designed after seeing the in-sample result above; disclosed, counted as 2 extra trials)\n")
    md.append("Mean-variance rule: w_t = scale × max(E[r_t | VIX_(t−1)], 0) / Var_(t−1), with E[r|VIX] from an expanding-window regression using only days before t "
              f"(5-year burn-in) and Var from trailing-{63}-day realised vol. Benchmark: vol-targeted book with no VIX information (Moreira–Muir).\n")
    for u in ("big_rev", "st_rev"):
        ph = is_res["post_hoc"][u]
        md.append(f"**{LABEL[u]}**, {ph['start']} → {ph['end']}\n")
        md.append("| | Constant | Vol-targeted | Mean-variance |\n|---|---|---|---|")
        for name, key, fmt in [("Ann. return (net)", "ann_return_net", _pct), ("Volatility", "ann_vol", _pct), ("Sharpe (net)", "sharpe_net", _f),
                               ("Sharpe (gross)", "sharpe_gross", _f), ("Max drawdown", "max_drawdown", _pct), ("Worst month", "worst_month", _pct),
                               ("Skew", "skew", _f), ("Turnover / yr", "turnover_per_year", lambda x: _f(x, 1)), ("Mean exposure", "mean_exposure", _f)]:
            md.append(f"| {name} | " + " | ".join(fmt(ph[k][key]) for k in ("constant", "vol_target", "mean_variance")) + " |")
        a, b = ph["mean_variance_vs_vol_target"], ph["mean_variance_vs_constant"]
        fa = ph["factor_alpha_mean_variance"]
        md.append(f"\nMean-variance vs vol-target: alpha {a['alpha_bps_per_day']:.2f} bps/day (t = {a['t_alpha_nw']:.2f}); vs constant: {b['alpha_bps_per_day']:.2f} bps/day (t = {b['t_alpha_nw']:.2f}). "
                  f"FF5+Mom alpha {fa['alpha_ann']*100:.2f}%/yr (t = {fa['t_alpha_nw']:.2f}), market beta {fa['beta_mkt_rf']:.3f}. "
                  f"Break-even c_base {ph['breakeven_c_base_bps_mean_variance']:.1f} bps. Exposure: mean {ph['mean_variance_exposure']['mean_exposure']:.2f}, "
                  f"max {ph['mean_variance_exposure']['max_exposure']:.2f}, {ph['mean_variance_exposure']['share_days_at_cap']*100:.1f}% of days at the cap.\n")
        md.append("Net return by year (mean-variance / vol-target):\n")
        md.append("| " + " | ".join(str(y) for y in ph["by_year_mean_variance"]) + " |\n|" + "---|" * len(ph["by_year_mean_variance"]))
        md.append("| " + " | ".join(f"{v*100:.0f}%" for v in ph["by_year_mean_variance"].values()) + " |")
        md.append("| " + " | ".join(f"{v*100:.0f}%" for v in ph["by_year_vol_target"].values()) + " |\n")

    md.append(f"\n## Multiple testing — {is_res['n_trials_total']} trials in total (36 pre-registered + 2 post-hoc)\n")
    md.append("| Strategy | net Sharpe | luck alone predicts best of N | P(true Sharpe > luck) |\n|---|---|---|---|")
    for u in ("big_rev", "st_rev"):
        for k, lab in (("headline", "VIX-timed headline"), ("mean_variance", "mean-variance (post-hoc)")):
            d = is_res[f"deflated_sharpe_{k}_{u}"]
            sr = is_res["strategies"][u]["timed"]["sharpe_net"] if k == "headline" else is_res["post_hoc"][u]["mean_variance"]["sharpe_net"]
            md.append(f"| {LABEL[u]}, {lab} | {sr:.2f} | {d['expected_max_sharpe_from_luck_ann']:.2f} | {d['deflated_sharpe_prob']:.3f} |")

    if oos_res:
        md.append(f"\n## OUT-OF-SAMPLE — {oos_res['start']} → {oos_res['end']} ({oos_res['n_days']} days), evaluated once at {oos_res['evaluated_utc']}\n")
        md.append("Pre-registered rules:\n")
        md.append("| | " + " | ".join(f"{LABEL[u]} constant | {LABEL[u]} timed" for u in ("big_rev", "st_rev")) + " |\n|---|---|---|---|---|")
        for name, key, fmt in [("Ann. return (net)", "ann_return_net", _pct), ("Volatility", "ann_vol", _pct), ("Sharpe (net)", "sharpe_net", _f),
                               ("Sharpe (gross)", "sharpe_gross", _f), ("Max drawdown", "max_drawdown", _pct), ("Worst month", "worst_month", _pct),
                               ("Turnover / yr", "turnover_per_year", lambda x: _f(x, 1))]:
            md.append(f"| {name} | " + " | ".join(f"{fmt(oos_res['strategies'][u]['constant'][key])} | {fmt(oos_res['strategies'][u]['timed'][key])}" for u in ("big_rev", "st_rev")) + " |")
        for u in ("big_rev", "st_rev"):
            r = oos_res["prediction_1_regression"][u]
            md.append(f"\n{LABEL[u]}: OOS slope on VIX_(t−1) = {r['slope_bps_per_vix_pt']:.3f} bps/pt (NW t = {r['t_slope_nw']:.2f}); "
                      f"timed-vs-constant alpha {oos_res['strategies'][u]['timed_vs_constant']['alpha_bps_per_day']:.2f} bps/day (t = {oos_res['strategies'][u]['timed_vs_constant']['t_alpha_nw']:.2f}).")
        md.append("\nOOS mean next-day return by lagged-VIX quintile (bps; quintiles within the OOS period):\n")
        md.append("| Quintile | VIX range | " + " | ".join(LABEL[u] for u in ("st_rev", "big_rev")) + " |\n|---|---|---|---|")
        for a, b in zip(oos_res["prediction_2_quintiles"]["st_rev"], oos_res["prediction_2_quintiles"]["big_rev"]):
            md.append(f"| Q{a['vix_quintile']} | {a['vix_lo']:.1f}–{a['vix_hi']:.1f} | {a['mean_bps']:.2f} ± {1.96*a['se_bps']:.2f} | {b['mean_bps']:.2f} ± {1.96*b['se_bps']:.2f} |")
        if "prediction_2_quintiles_in_sample_edges" in oos_res:
            e = oos_res["in_sample_edges"]
            md.append(f"\nOOS mean next-day return binned on the IN-SAMPLE VIX quintile edges ({', '.join(f'{x:.1f}' for x in e[1:-1])}):\n")
            md.append("| Bin | VIX range | " + " | ".join(f"{LABEL[u]} mean ± 95% CI (n)" for u in ("st_rev", "big_rev")) + " |\n|---|---|---|---|")
            for a, b in zip(oos_res["prediction_2_quintiles_in_sample_edges"]["st_rev"], oos_res["prediction_2_quintiles_in_sample_edges"]["big_rev"]):
                if a["n_days"] == 0:
                    continue
                md.append(f"| Q{a['vix_quintile']} | {a['vix_lo']:.1f}–{a['vix_hi']:.1f} | {a['mean_bps']:.2f} ± {1.96*a['se_bps']:.2f} ({a['n_days']}) | {b['mean_bps']:.2f} ± {1.96*b['se_bps']:.2f} ({b['n_days']}) |")
        md.append("\nPost-hoc rules (same held-out days):\n")
        md.append("| | " + " | ".join(f"{LABEL[u]} vol-target | {LABEL[u]} mean-variance" for u in ("big_rev", "st_rev")) + " |\n|---|---|---|---|---|")
        for name, key, fmt in [("Ann. return (net)", "ann_return_net", _pct), ("Volatility", "ann_vol", _pct), ("Sharpe (net)", "sharpe_net", _f),
                               ("Max drawdown", "max_drawdown", _pct), ("Mean exposure", "mean_exposure", _f)]:
            md.append(f"| {name} | " + " | ".join(f"{fmt(oos_res['post_hoc'][u]['vol_target'][key])} | {fmt(oos_res['post_hoc'][u]['mean_variance'][key])}" for u in ("big_rev", "st_rev")) + " |")
    (out_dir / "REPORT.md").write_text("\n".join(md) + "\n")
