"""Render results/REPORT_B.md (Module B) from the JSON results."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from . import config
from .gapfade import C_BASE_BPS, DOLLARS_TRADED_PER_DAY, N_VARIANTS, VIX_THRESHOLD


def _pct(x): return f"{x*100:.2f}%"


def _strat_table(strat: dict) -> str:
    rows = [("Ann. return (net)", "ann_return_net", _pct), ("Ann. return (gross)", "ann_return_gross", _pct),
            ("Cost drag / yr", "ann_cost_drag", _pct), ("Volatility", "ann_vol", _pct),
            ("Sharpe (net)", "sharpe_net", lambda x: f"{x:.2f}"), ("Sharpe (gross)", "sharpe_gross", lambda x: f"{x:.2f}"),
            ("Mean net, bps/day (all days)", "mean_net_bps", lambda x: f"{x:.2f}"),
            ("NW t of mean net", "t_mean_net_nw", lambda x: f"{x:.2f}"),
            ("Mean net, bps/day (days on)", "mean_net_bps_on_days", lambda x: f"{x:.2f}"),
            ("Max drawdown", "max_drawdown", _pct), ("Worst month", "worst_month", _pct), ("Worst day", "worst_day", _pct),
            ("Share of days on", "share_days_on", _pct), ("Days on", "n_days_on", lambda x: f"{x:,}")]
    md = "| | Always on | VIX≥20 participation (headline) |\n|---|---|---|\n"
    for name, key, fmt in rows:
        md += f"| {name} | {fmt(strat['always_on'][key])} | {fmt(strat['participation'][key])} |\n"
    return md


def _quintiles(records: list[dict], min_n: int = 10) -> str:
    md = "| VIX quintile (IS edges) | VIX range | gross spread mean ± 95% CI (bps) | ann. SR gross | worst day | N |\n|---|---|---|---|---|---|\n"
    for r in records:
        if r["n_days"] < min_n:
            continue
        md += (f"| Q{r['vix_quintile']} | {r['vix_lo']:.1f}–{r['vix_hi']:.1f} | {r['mean_bps']:.2f} ± {1.96*r['se_bps']:.2f} | "
               f"{r['ann_sharpe']:.2f} | {r['worst_day_bps']/100:.1f}% | {r['n_days']:,} |\n")
    return md


def _grid(records: list[dict]) -> str:
    df = pd.DataFrame(records)
    md = "| sort | c_base (bps) | threshold | net Sharpe | ann. net return | mean net bps/day | NW t | share days on |\n|---|---|---|---|---|---|---|---|\n"
    for _, r in df.iterrows():
        md += (f"| {r['sort']} | {r['c_base_bps']:g} | {r['threshold']} | {r['sharpe_net']:.2f} | {r['ann_return_net']*100:.1f}% | "
               f"{r['mean_net_bps']:.2f} | {r['t_mean_net_nw']:.2f} | {r['share_days_on']*100:.0f}% |\n")
    return md


def write_report_b(is_res: dict, oos_res: dict | None, out_dir: Path) -> None:
    T, S = is_res["hypothesis_tests"], is_res["strategies"]
    md = ["# Module B results report (auto-generated by `run_all.py`)\n",
          f"Generated {is_res['generated_utc']}. In-sample {is_res['start']} → {is_res['end']} ({is_res['n_days']:,} days, "
          f"mean {T['mean_names_per_day']:.0f} eligible names/day). Held-out {config.OOS_START.date()} → {config.OOS_END.date()}"
          + (" — **evaluated**." if oos_res else " — **locked, not evaluated in this run**.") + "\n",
          f"Book: $1 long largest relative gap-down quintile, $1 short largest gap-up quintile, open→close. "
          f"Cost: {DOLLARS_TRADED_PER_DAY:.0f} × {C_BASE_BPS:g} bps × VIX_(t−1)/20 per day. Rule: on iff VIX_(t−1) ≥ {VIX_THRESHOLD:g}.\n",
          "## B1 — gross spread\n",
          f"Mean {T['B1_gross_spread']['mean_bps']:.2f} bps/day, NW t = {T['B1_gross_spread']['t_nw']:.2f}, gross annualised Sharpe "
          f"{T['B1_gross_spread']['ann_sharpe_gross']:.2f}, N = {T['B1_gross_spread']['n']:,}.\n",
          "## B2 — dependence on lagged VIX\n",
          f"Slope {T['B2_slope_on_vix']['slope_bps_per_vix_pt']:.3f} bps per VIX point, NW t = {T['B2_slope_on_vix']['t_slope_nw']:.2f} "
          f"(p = {T['B2_slope_on_vix']['p_slope']:.4f}), R² = {T['B2_slope_on_vix']['r2']:.4f}.\n",
          _quintiles(T["B2_vix_quintiles"]),
          "\n## B4 — which leg earns it (excess over equal-weighted universe open→close return)\n",
          f"Long gap-down leg: {T['B4_legs']['long_leg_excess_bps']['mean_bps']:.2f} bps/day (t = {T['B4_legs']['long_leg_excess_bps']['t_nw']:.2f}); "
          f"short gap-up leg: {T['B4_legs']['short_leg_excess_bps']['mean_bps']:.2f} bps/day (t = {T['B4_legs']['short_leg_excess_bps']['t_nw']:.2f}).\n",
          "| VIX quintile | long leg excess (bps) | short leg excess (bps) |\n|---|---|---|"]
    for r in T["B4_legs_by_vix_quintile"]:
        md.append(f"| Q{r['vix_lag']} | {r['long_leg_excess_bps']:.2f} | {r['short_leg_excess_bps']:.2f} |")
    md += ["\n## B3 — net of costs, in-sample\n", _strat_table(S),
           f"\nParticipation vs always-on (spanning regression, HAC): alpha {S['B3_participation_vs_always_on']['alpha_bps_per_day']:.2f} bps/day, "
           f"t = {S['B3_participation_vs_always_on']['t_alpha_nw']:.2f}. Break-even c_base: always-on {S['breakeven_c_base_bps_always_on']:.2f} bps, "
           f"participation {S['breakeven_c_base_bps_participation']:.2f} bps.\n",
           "### Net return by year\n", "| Year | Always on | Participation |\n|---|---|---|"]
    for y in S["by_year_always_on_net"]:
        md.append(f"| {y} | {S['by_year_always_on_net'][y]*100:.1f}% | {S['by_year_participation_net'].get(y, 0)*100:.1f}% |")
    md += ["\n## B5 — pre-registered sensitivity grid (" + str(N_VARIANTS) + " variants, all shown)\n", _grid(is_res["sensitivity_grid"]),
           "\n## Post-hoc descriptive: sub-periods (decided after the by-year table was seen)\n",
           "| Period | N | gross mean (bps) | NW t | slope on VIX | t | VIX Q1 mean | VIX Q5 mean | net SR always | net SR participation | break-even always / participation |\n|---|---|---|---|---|---|---|---|---|---|---|"]
    for k, v in is_res["subperiods_post_hoc_descriptive"].items():
        md.append(f"| {k} | {v['n_days']:,} | {v['gross_mean_bps']:.2f} | {v['t_nw']:.2f} | {v['slope_bps_per_vix_pt']:.2f} | {v['t_slope_nw']:.2f} | "
                  f"{v['vix_q1_mean_bps']:.1f} | {v['vix_q5_mean_bps']:.1f} | {v['sharpe_net_always_on']:.2f} | {v['sharpe_net_participation']:.2f} | "
                  f"{v['breakeven_c_base_bps_always_on']:.1f} / {v['breakeven_c_base_bps_participation']:.1f} bps |")
    u = is_res["unfiltered_gap_robustness"]
    md.append(f"\nWithout the |gap| > 20% cleaning rule: gross mean {u['gross_spread_mean_bps']:.2f} bps (t = {u['t_nw']:.2f}), "
              f"net Sharpe always-on {u['sharpe_net_always_on']:.2f}, participation {u['sharpe_net_participation']:.2f}.\n")
    if oos_res:
        TO, SO = oos_res["hypothesis_tests"], oos_res["strategies"]
        md += [f"\n## OUT-OF-SAMPLE {oos_res['start']} → {oos_res['end']} ({oos_res['n_days']} days) — evaluated once\n",
               f"B1: gross spread {TO['B1_gross_spread']['mean_bps']:.2f} bps/day, NW t = {TO['B1_gross_spread']['t_nw']:.2f}, gross SR {TO['B1_gross_spread']['ann_sharpe_gross']:.2f}.\n",
               f"B2: slope {TO['B2_slope_on_vix']['slope_bps_per_vix_pt']:.3f} bps/VIX pt, NW t = {TO['B2_slope_on_vix']['t_slope_nw']:.2f}.\n",
               _quintiles(TO["B2_vix_quintiles"]),
               f"\nB4: long leg {TO['B4_legs']['long_leg_excess_bps']['mean_bps']:.2f} bps (t = {TO['B4_legs']['long_leg_excess_bps']['t_nw']:.2f}), "
               f"short leg {TO['B4_legs']['short_leg_excess_bps']['mean_bps']:.2f} bps (t = {TO['B4_legs']['short_leg_excess_bps']['t_nw']:.2f}).\n",
               "\nB3, net of costs:\n", _strat_table(SO),
               f"\nParticipation vs always-on: alpha {SO['B3_participation_vs_always_on']['alpha_bps_per_day']:.2f} bps/day, t = {SO['B3_participation_vs_always_on']['t_alpha_nw']:.2f}. "
               f"Break-even c_base: always-on {SO['breakeven_c_base_bps_always_on']:.2f} bps, participation {SO['breakeven_c_base_bps_participation']:.2f} bps.\n",
               "\n### Out-of-sample grid\n", _grid(oos_res["sensitivity_grid"])]
    (out_dir / "REPORT_B.md").write_text("\n".join(md) + "\n")
